import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import ScrollProgress from "@/components/ScrollProgress";
import GoogleTranslate from "@/components/GoogleTranslate";
import WhatsappChat from "@/components/WhatsappChat";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[var(--secondary)]"
        
      >
          <ScrollProgress />  
        <Navbar />
        {children}
        <ScrollToTop/>
         
        <Footer />
          <WhatsappChat/>
      </body>
    </html>
  );
}
